apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: 933391749616.dkr.ecr.us-east-1.amazonaws.com/udacity-p4-backend:latest
          ports:
            - containerPort: 3000
