name: Backend Continuous Integration

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./starter/backend
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12

    - name: Install Pipenv
      run: |
        python -m pip install --upgrade pip
        pip install pipenv flask_cors flake8

    - name: Run linting
      run: pipenv run lint

  test:
    runs-on: ubuntu-latest
    needs: [lint]
    defaults:
      run:
        working-directory: ./starter/backend
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12

    - name: Install Pipenv
      run: |
        python -m pip install --upgrade pip
        pip install pipenv flask_cors flake8 pytest

    - name: Run tests
      run: pipenv run test
