name: Frontend Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./starter/frontend
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      with:
        mask-password: 'true'

    - name: Build and push ECR image
      run: |
          docker build -t env.$ECR_NAME .
          docker tag env.$ECR_NAME:latest env.$ECR_REPOSITORY/env.$ECR_NAME:latest
          docker push env.$ECR_REPOSITORY/env.$ECR_NAME:latest

    # - name: Set up kubectl
    #   uses: azure/setup-kubectl@v2
    #   with:
    #     version: 'latest'

    # - name: Deploy to Kubernetes
    #   run: |
    #     echo "${{ secrets.KUBECONFIG }}" > kubeconfig.yaml
    #     kubectl apply -f deployment.yml --kubeconfig=kubeconfig.yaml
